[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# -----------------
# 1. 패키지 기본 정보
# -----------------
[project]
name = "sayou-visualizer"
version = "0.0.9"
authors = [
    { name = "Sayouzone", email = "contact@sayouzone.com" },
]
description = "Visualizer components for the Sayou Data Platform"
readme = "README.md"
license = { file = "../../LICENSE" }
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]
dependencies = [
    "sayou-core ~= 0.3.0",
    "networkx == 3.2.1",
    "pyvis == 0.3.2",
    "rich == 14.2.0",
    "websocket-client == 1.9.0"
]

# -----------------
# 2. 프로젝트 링크 (PyPI 사이드바)
# -----------------
[project.urls]
"Homepage" = "https://www.sayouzone.com/"
"Documentation" = "https://sayouzone.github.io/sayou-fabric/"
"Repository" = "https://github.com/sayouzone/sayou-fabric"

# -----------------
# 3. 소스 코드 위치
# -----------------
[tool.hatch.build.targets.wheel]
packages = ["src/sayou"]